on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check it out now
        uses: actions/checkout@v2

      - name: Funk
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/dwd/doh-proxy:testing

      - name: Soul Brother
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: ./doh-proxy-test.sh

      - name: Check it out now
        run: dig @${{ secrets.TEST_DEPLOY }} +https google.co.uk

      - name: Funk
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/dwd/doh-proxy:latest

      - name: Soul
        uses: applyboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: ./doh-proxy-deploy.sh

      - name: Brother
        uses: applyboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: ./doh-proxy-deploy.sh

      - name: Check it out now
        run: dig @${{ secrets.TEST_DEPLOY }} +https google.co.uk
