on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check it out now
        uses: actions/checkout@v2

      - name: Funk
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: dwd
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Soul
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/dwd/doh-proxy:testing

      - name: Soul Brother
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker compose pull doh-test
            docker compose rm --stop --force doh-test
            docker compose up -d doh-test

      - name: Check it out now
        run: dig @${{ secrets.TEST_DEPLOY }} +https google.co.uk

      - name: Funk
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/dwd/doh-proxy:live

      - name: Soul
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker compose pull doh-live
            docker compose rm --stop --force doh-live
            docker compose up -d doh-live

      - name: Brother
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker compose pull doh-live
            docker compose rm --stop --force doh-live
            docker compose up -d doh-live

      - name: Check it out now
        run: dig @${{ secrets.MAIN_DEPLOY }} +https google.co.uk
